# -*- coding: utf-8 -*-
"""
report_body.py — corpo do Relatório de Prontidão para Lançamento
do Diário da Riqueza (ReportLab, sem capa; capa é HTML/Playwright
mesclada depois via pypdf).

Pipeline: TocDocTemplate + multiBuild (TOC automático).
Numeração: Sumário = i (romano); corpo = arábico reiniciado em 1.
"""
import hashlib
import os
import sys

SKILL_DIR = '/home/z/my-project/skills/pdf'
sys.path.insert(0, os.path.join(SKILL_DIR, 'scripts'))

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (CondPageBreak, KeepTogether, PageBreak,
                                Paragraph, SimpleDocTemplate, Spacer, Table,
                                TableStyle)
from reportlab.platypus.tableofcontents import TableOfContents

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f5f5f5')
SECTION_BG    = colors.HexColor('#efefed')
CARD_BG       = colors.HexColor('#e7e6e4')
TABLE_STRIPE  = colors.HexColor('#f3f2f1')
HEADER_FILL   = colors.HexColor('#625a43')
COVER_BLOCK   = colors.HexColor('#7e755b')
BORDER        = colors.HexColor('#cec6af')
ICON          = colors.HexColor('#847032')
ACCENT        = colors.HexColor('#96771b')
ACCENT_2      = colors.HexColor('#7157bc')
TEXT_PRIMARY  = colors.HexColor('#242321')
TEXT_MUTED    = colors.HexColor('#8f8d86')
SEM_SUCCESS   = colors.HexColor('#4b9764')
SEM_WARNING   = colors.HexColor('#9a804d')
SEM_ERROR     = colors.HexColor('#a94b43')
SEM_INFO      = colors.HexColor('#496886')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = TABLE_STRIPE

# ── Fontes (somente as permitidas) ──
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback  # noqa: E402
install_font_fallback()

# ── Documento ──
MARGIN = 0.9 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN = AVAIL_H * 0.25
OUT = '/home/z/my-project/scripts/out/relatorio_corpo.pdf'
os.makedirs(os.path.dirname(OUT), exist_ok=True)

DOC_TITLE = 'Relatório de Prontidão para Lançamento — Diário da Riqueza'


class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            # Exibido = interno - 1 (página 1 interna é o Sumário, romano i)
            self.notify('TOCEntry', (level, text, self.page - 1, key))


def footer(canvas, doc):
    canvas.saveState()
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, 'Diário da Riqueza — Auditoria técnica de lançamento')
    if doc.page == 1:
        num = 'i'
    else:
        num = str(doc.page - 1)
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, num)
    # cabeçalho
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    canvas.restoreState()


# ── Estilos ──
body = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=17,
                      alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
                      spaceBefore=0, spaceAfter=8)
h1 = ParagraphStyle('H1', fontName='FreeSerif', fontSize=20, leading=26,
                    textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=10)
h2 = ParagraphStyle('H2', fontName='FreeSerif', fontSize=14, leading=20,
                    textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
bullet = ParagraphStyle('Bullet', fontName='FreeSerif', fontSize=10.5, leading=16,
                        alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                        leftIndent=14, bulletIndent=2, spaceAfter=5)
caption = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5, leading=12,
                         alignment=TA_CENTER, textColor=TEXT_MUTED,
                         spaceBefore=3, spaceAfter=6)
quote = ParagraphStyle('Quote', fontName='FreeSerif-Italic', fontSize=11, leading=18,
                       alignment=TA_LEFT, textColor=TEXT_PRIMARY, leftIndent=24,
                       borderPadding=6, spaceBefore=10, spaceAfter=10)
th = ParagraphStyle('TH', fontName='FreeSerif', fontSize=9.5, leading=13,
                    textColor=colors.white, alignment=TA_LEFT)
td = ParagraphStyle('TD', fontName='FreeSerif', fontSize=9.5, leading=13.5,
                    textColor=TEXT_PRIMARY, alignment=TA_LEFT)
td_c = ParagraphStyle('TDC', parent=td, alignment=TA_CENTER)
stat_big = ParagraphStyle('StatBig', fontName='FreeSerif', fontSize=19, leading=23,
                          textColor=ACCENT, alignment=TA_CENTER)
stat_lbl = ParagraphStyle('StatLbl', fontName='FreeSerif', fontSize=8.5, leading=11.5,
                          textColor=TEXT_MUTED, alignment=TA_CENTER)


def heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def section(story_list, num, title):
    story_list.append(CondPageBreak(H1_ORPHAN))
    story_list.append(heading('%d. %s' % (num, title), h1, level=0))


def para(text):
    return Paragraph(text, body)


def bullets(items):
    return [Paragraph(it, bullet, bulletText='•') for it in items]


def make_table(headers, rows, ratios, align_center_cols=()):
    col_w = [r * AVAIL_W for r in ratios]
    assert sum(col_w) <= AVAIL_W + 0.5
    data = [[Paragraph('<b>%s</b>' % c, th) for c in headers]]
    for row in rows:
        cells = []
        for i, c in enumerate(row):
            st = td_c if i in align_center_cols else td
            cells.append(Paragraph(c, st))
        data.append(cells)
    t = Table(data, colWidths=col_w, hAlign='CENTER', repeatRows=1)
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 7),
        ('RIGHTPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 5.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5.5),
    ]
    for r in range(1, len(data)):
        style.append(('BACKGROUND', (0, r), (-1, r),
                      TABLE_ROW_ODD if r % 2 == 0 else TABLE_ROW_EVEN))
    t.setStyle(TableStyle(style))
    return t


def callout_row(stats):
    """Linha de 3 stat-boxes (CalloutBox pattern)."""
    boxes = []
    w = (AVAIL_W - 24) / 3.0
    for value, label in stats:
        inner = Table([[Paragraph('<b>%s</b>' % value, stat_big)],
                       [Paragraph(label, stat_lbl)]], colWidths=[w])
        inner.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), SECTION_BG),
            ('BOX', (0, 0), (-1, -1), 1, ACCENT),
            ('TOPPADDING', (0, 0), (-1, 0), 9),
            ('BOTTOMPADDING', (0, 1), (-1, 1), 9),
            ('TOPPADDING', (0, 1), (-1, 1), 2),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 2),
        ]))
        boxes.append(inner)
    outer = Table([boxes], colWidths=[w + 12] * 3, hAlign='CENTER')
    outer.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    return outer


story = []

# ── Sumário (página i) ──
story.append(Paragraph('<b>Sumário</b>', ParagraphStyle(
    'TocTitle', parent=h1, fontSize=22, spaceBefore=6, spaceAfter=14)))
toc = TableOfContents()
toc.levelStyles = [
    ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=11.5, leading=20,
                   leftIndent=16, textColor=TEXT_PRIMARY),
]
story.append(toc)
story.append(PageBreak())

# ══════════════ CAPÍTULO 1 — RESUMO EXECUTIVO ══════════════
section(story, 1, 'Resumo executivo e veredicto')
story.append(para(
    'Esta auditoria avaliou o Diário da Riqueza sob duas perguntas feitas pelo '
    'operador: o aplicativo está pronto para ser divulgado nas redes sociais, e '
    'está pronto para ser usado por muitas pessoas ao mesmo tempo? A análise '
    'combinou quatro frentes de verificação: revisão do código-fonte (metadados, '
    'PWA, APIs, autenticação), testes diretos em produção (latências, cache de '
    'CDN, cabeçalhos), navegação end-to-end automatizada simulando um usuário '
    'real do primeiro clique até o registro diário, e varredura de segurança no '
    'pacote JavaScript entregue ao navegador.'))
story.append(Spacer(1, 6))
story.append(callout_row([
    ('PRONTA', 'Veredicto geral — pode divulgar'),
    ('346', 'Testes automatizados, 0 falhas'),
    ('0', 'Segredos expostos no bundle público'),
]))
story.append(Spacer(1, 10))
story.append(para(
    'O veredicto é <b>positivo: o aplicativo está pronto para divulgação</b>. O '
    'fluxo essencial — chegada pela landing page, criação do diário em 5 passos, '
    'registro do dia com XP e conquista — funciona de ponta a ponta em produção, '
    'inclusive offline. Durante a própria auditoria, três lacunas que fragilizariam '
    'a primeira impressão pública foram identificadas e corrigidas no mesmo dia: '
    'inexistência de páginas de Política de Privacidade e Termos de Uso, ausência '
    'de sitemap.xml para indexação e um erro 404 sem identidade visual. Todas '
    'corrigidas, implantadas e verificadas em produção.'))
story.append(KeepTogether([
    Paragraph('<b>Quadro de prontidão por dimensão</b>', h2),
    make_table(
        ['Dimensão', 'Nota', 'Situação verificada'],
        [
            ['Funcionalidade e qualidade', '9,5', '346 testes verdes; E2E limpo, zero erros de console'],
            ['PWA e funcionamento offline', '9,5', 'Instalável; service worker ativo; recarga offline funcional'],
            ['Compartilhamento social (SEO/OG)', '9,0', 'og:image 1200×630 real; cartão Twitter completo; pt-BR'],
            ['Segurança', '9,0', 'Admin com auth e rate limit; webhook timing-safe; bundle limpo'],
            ['Confiança e conformidade (LGPD)', '9,0', 'Privacidade e Termos publicados; dados 100% locais'],
            ['Escalabilidade', '8,5', 'Local-first escala bem; CDN cache ativo; Hobby tem limite de banda'],
            ['Acessibilidade', '7,5', 'Boa navegação semântica; zoom de página bloqueado (ajuste fino)'],
        ],
        [0.34, 0.10, 0.56], align_center_cols=(1,)),
]))
story.append(Paragraph('Quadro 1 — Scorecard consolidado da auditoria (notas de 0 a 10).', caption))

# ══════════════ CAPÍTULO 2 — METODOLOGIA ══════════════
section(story, 2, 'Metodologia da auditoria')
story.append(para(
    'A avaliação foi executada em quatro camadas complementares, para que o '
    'veredicto não dependa de uma única fonte de evidência. A camada de código '
    'revisou os arquivos responsáveis por metadados, manifesto PWA, robots.txt, '
    'rotas de API, autenticação administrativa e componentes públicos. A camada '
    'de infraestrutura mediu tempos de resposta reais das rotas críticas em '
    'produção, comportamento do cache de CDN e disponibilidade dos arquivos '
    'estáticos (ícones, manifest, service worker).'))
story.append(para(
    'A camada de experiência simulou um usuário novo por navegador automatizado: '
    'abriu a landing page, percorreu o onboarding completo (nome, meta financeira '
    'de R$ 100.000 com prazo 31/12/2030, aparência), criou o diário, registrou '
    'uma entrada com aprendizado e reflexão, recebeu o feedback de gamificação '
    '(+90 XP e conquista Primeiro Passo) e passou por testes de recarga offline '
    'e viewport móvel de 390 pixels. Por fim, a camada de segurança varreu o '
    'bundle JavaScript público procurando segredos: senha administrativa, '
    'credenciais Cakto, token Vercel e chaves de API.'))

# ══════════════ CAPÍTULO 3 — REDES SOCIAIS ══════════════
section(story, 3, 'Prontidão para divulgação nas redes sociais')
story.append(para(
    'Quando um link é compartilhado no WhatsApp, Instagram, Facebook ou X, a '
    'plataforma busca as meta tags Open Graph para montar o cartão de preview. '
    'O Diário da Riqueza entrega o conjunto completo: título e descrição em '
    'português, imagem de 1200×630 pixels (47 KB, PNG real verificado), texto '
    'alternativo descritivo, localização pt_BR e cartão Twitter no modo '
    'summary_large_image com imagem própria. Isso significa que quem recebe o '
    'link vê um cartão profissional com a identidade preto e dourado — não um '
    'link nu.'))
story.append(para(
    'A landing page em si funciona como página de conversão para tráfego frio: '
    'proposta de valor acima da dobra, chamada "Começar gratuitamente" repetida '
    'em três pontos, seção de transparência ("o que a ferramenta não promete") '
    'que protege a credibilidade, prova social permanente com o Mural dos '
    'Fundadores e o letreiro vermelho rolante com 76 nomes, e rodapé com todos '
    'os canais do criador. Os bots sociais (Twitterbot, facebookexternalhit) '
    'estão expressamente permitidos no robots.txt, enquanto painel administrativo '
    'e APIs permanecem fora dos índices.'))
story.append(KeepTogether([
    Paragraph('<b>Verificações de compartilhamento social</b>', h2),
    make_table(
        ['Item', 'Resultado', 'Detalhe'],
        [
            ['og:image', 'Aprovado', 'PNG 1200×630, 47 KB, servida com 200 e alt text'],
            ['twitter:card', 'Aprovado', 'summary_large_image + imagem e descrição próprias'],
            ['Título e descrição', 'Aprovado', 'Únicos, em pt-BR, com palavras-chave do nicho'],
            ['robots.txt', 'Aprovado', 'Permite bots sociais; bloqueia /admin e /api'],
            ['sitemap.xml', 'Aprovado', 'Criado nesta auditoria (3 URLs indexáveis)'],
            ['Páginas legais', 'Aprovado', '/privacidade e /termos criadas e linkadas no rodapé'],
            ['Compartilhar no app', 'Aprovado', 'ShareDialog com navigator.share para redes'],
        ],
        [0.28, 0.14, 0.58]),
]))
story.append(Paragraph('Quadro 2 — Itens de prontidão social verificados em produção.', caption))
story.append(para(
    'Um detalhe que costuma passar despercebido: a divisa de entrada de quem '
    'chega das redes é a página inicial carregada pelo CDN com TTFB de 87 '
    'milissegundos na segunda visita e cerca de 1,3 s no primeiro acesso (start '
    'a frio do servidor sem fio). Para padrão de rede social isso é confortável, '
    'e o cartão de preview bem-feito é o que sustenta a taxa de cliques.'))

# ══════════════ CAPÍTULO 4 — ESCALA ══════════════
section(story, 4, 'Prontidão para uso por muitas pessoas')
story.append(para(
    'A arquitetura é a maior aliada aqui: por ser local-first, cada usuário carrega '
    'seus dados no próprio dispositivo (IndexedDB) e o servidor não armazena '
    'nada de conteúdo. Não existe banco de dados central para estourar, não '
    'existe autenticação de usuários para escalar, e cada visita custa entrega '
    'estática na borda da Vercel. Um pico de dez mil visitas simultâneas degrada '
    'muito menos do que em uma aplicação tradicional com backend e banco.'))
story.append(para(
    'A única rota pública que consulta serviço externo é a do Mural dos '
    'Fundadores, e ela foi projetada para isso: cache duplo (memória de 5 '
    'minutos no servidor + CDN com s-maxage de 300 segundos e stale-while-'
    'revalidate de 30 minutos). A auditoria confirmou o cache de CDN em '
    'operação — a segunda chamada consecutiva retornou HIT sem tocar a origem. '
    'Mesmo se a Cakto ficar indisponível, a rota responde 200 com estado '
    'honesto, sem derrubar a página.'))
story.append(callout_row([
    ('87 ms', 'TTFB da home no CDN (2ª visita)'),
    ('HIT', 'Cache de CDN na rota /api/founders'),
    ('390 px', 'Mobile testado: sem scroll horizontal'),
]))
story.append(Spacer(1, 10))
story.append(para(
    'O plano Vercel Hobby tem 100 GB de banda mensal. Com primeira carga em '
    'torno de 1 MB por visitante novo (visitas recorrentes consomem bem menos '
    'por causa do cache do service worker), isso corresponde a dezenas de '
    'milhares de novos acessos por mês — folga confortável para um lançamento '
    'em redes sociais. Se o projeto crescer além disso, o upgrade Pro é '
    'operacionalmente trivial: nenhuma mudança de código é necessária.'))
story.append(para(
    'O funcionamento offline foi provado em produção: com a rede desligada no '
    'navegador, a recarga entregou o shell completo do aplicativo a partir do '
    'cache (estratégia network-first para navegações, cache-first para estáticos '
    'e stale-while-revalidate para o restante). Um usuário que salva o app na '
    'tela inicial do celular continua usando todas as funções principais sem '
    'internet — argumento de venda que merece destaque na divulgação.'))

# ══════════════ CAPÍTULO 5 — SEGURANÇA ══════════════
section(story, 5, 'Segurança e conformidade')
story.append(para(
    'A superfície administrativa ficou bem protegida: o painel /admin responde '
    '307 e exige login com e-mail e senha, comparação timing-safe em ambos os '
    'campos, sessão assinada por HMAC com cookie httpOnly de 8 horas e limite '
    'de 5 tentativas por 15 minutos por IP. O webhook da Cakto valida um token '
    'compartilhado com comparação timing-safe, e todas as credenciais vivem '
    'exclusivamente em variáveis de ambiente do servidor.'))
story.append(para(
    'A varredura do bundle público procurou a senha administrativa, o e-mail de '
    'administração, o token Vercel e segredos da Cakto: nada encontrado. A única '
    'ocorrência do identificador "clodoaldo608" é o link público do Linktree no '
    'rodapé, de propósito. Em paralelo, as páginas de Política de Privacidade e '
    'Termos de Uso publicadas nesta auditoria documentam em linguagem clara o '
    'tratamento local-first dos dados, o papel da Cakto nos pagamentos, a '
    'política de exibição do mural e os direitos do titular na LGPD — com canal '
    'de contato e prazo de resposta.'))
story.append(para(
    'Resta uma dívida de segurança operacional, já sinalizada antes e mantida no '
    'plano de ação: a senha administrativa atual tem apenas oito dígitos '
    'numéricos. O rate limit torna força bruta impraticável no curto prazo, mas '
    'a troca por uma senha longa com letras, números e símbolos é um incremento '
    'de proteção de custo zero.'))

# ══════════════ CAPÍTULO 6 — EVIDÊNCIAS ══════════════
section(story, 6, 'Evidências de produção (E2E)')
story.append(para(
    'A tabela a seguir consolida as verificações executadas diretamente contra '
    'o ambiente de produção durante a auditoria. Tempos medidos em rede real; '
    'o E2E de usuário foi feito em navegador automatizado com coleta de erros '
    'de console ao longo de toda a sessão.'))
story.append(KeepTogether([
    make_table(
        ['Verificação', 'Resultado', 'Medição'],
        [
            ['Home em produção', '200', '1,36 s a frio; 87 ms TTFB em cache'],
            ['manifest.webmanifest', '200', 'Instalável, standalone, ícone maskable'],
            ['Service worker', 'Ativo', 'sw.js registrado; cache diario-riqueza-v1'],
            ['Recarga offline', 'OK', 'Shell completo servido sem rede'],
            ['og:image', '200', 'PNG 1200×630, 47 KB'],
            ['/api/founders', '200', '2,6 s a frio; HIT de CDN depois'],
            ['/admin sem sessão', '307', 'Redireciona para login; sem vazamento'],
            ['Onboarding 5 passos', 'OK', 'Nome, meta, pasta, tema, criação'],
            ['Registro diário', 'OK', '+90 XP, conquista Primeiro Passo'],
            ['Mobile 390 px', 'OK', 'Sem scroll horizontal; bottom nav'],
            ['Rotas legais novas', '200', '/privacidade, /termos, /sitemap.xml'],
            ['404 com marca', '404', 'Página personalizada com CTA para a home'],
        ],
        [0.36, 0.14, 0.50], align_center_cols=(1,)),
]))
story.append(Paragraph('Quadro 3 — Síntese das evidências coletadas em produção.', caption))

# ══════════════ CAPÍTULO 7 — RISCOS ══════════════
section(story, 7, 'Riscos e limitações conhecidas')
story.append(para(
    'Nenhum bloqueador permanece, mas há pontos que merecem acompanhamento '
    'consciente. São limitações conhecidas, documentadas e com mitigação '
    'definida — a lista existe para que a divulgação aconteça com clareza sobre '
    'o que o produto é hoje, e não por surpresa depois.'))
story.extend(bullets([
    '<b>Start a frio do serverless:</b> a primeira visita em um período ocioso '
    'pode levar de 1,3 s (home) a 2,6 s (/api/founders) a mais. O cache de CDN '
    'elimina o efeito para todo mundo que chega em seguida; mitigação natural '
    'com tráfego de redes.',
    '<b>Limite de banda do plano Hobby (100 GB/mês):</b> suficiente para o '
    'lançamento, mas um vídeo viral muito grande pode exigir o upgrade Pro no '
    'meio do mês. Custo baixo, mudança de um clique.',
    '<b>Sem analytics ainda:</b> hoje não há medição de visitantes, origem de '
    'tráfego nem conversão da landing. Para divulgação profissional, instalar '
    'o Vercel Analytics (sem cookies, LGPD-friendly) deveria ser o primeiro '
    'passo pós-auditoria.',
    '<b>Zoom de página bloqueado no navegador:</b> userScalable=false impede '
    'pinça de zoom, o que penaliza usuários com baixa visão. O app já é '
    'integralmente usável, mas liberar o zoom (ou oferecer ajuste de fonte) '
    'fecharia essa diferença de acessibilidade.',
    '<b>Recriar conta em outro dispositivo:</b> bug conhecido e de baixa '
    'severidade no fluxo de quem já tinha dados e tenta criar conta novamente '
    'em aparelho novo; dados locais não migram sozinhos — o backup/exportação '
    'cobre o cenário.',
]))
story.append(Paragraph(
    'Nenhuma dessas limitações impede a divulgação; todas têm caminho de '
    'resolução mapeado no capítulo seguinte.', body))

# ══════════════ CAPÍTULO 8 — PLANO DE AÇÃO ══════════════
section(story, 8, 'Plano de ação recomendado')
story.append(para(
    'Com o veredicto positivo, o plano abaixo ordena os próximos investimentos '
    'por impacto sobre o objetivo de crescer com redes sociais. Os itens P1 '
    'devem preceder a primeira campanha relevante; os demais podem acompanhar o '
    'ritmo de crescimento.'))
story.append(KeepTogether([
    make_table(
        ['Prioridade', 'Ação', 'Esforço', 'Impacto'],
        [
            ['P1', 'Instalar Vercel Analytics (visitantes, origem, conversão)', 'Baixo', 'Alto'],
            ['P1', 'Trocar a senha admin por senha longa com símbolos', 'Baixo', 'Médio'],
            ['P2', 'Domin próprio (ex.: diariodariqueza.com.br) + redirecionamento', 'Baixo', 'Alto'],
            ['P2', 'Monitoramento de uptime com alerta (UptimeRobot/Better Stack)', 'Baixo', 'Médio'],
            ['P2', 'Recriar o og:image com print real do app (prova visual maior)', 'Médio', 'Médio'],
            ['P3', 'Liberar zoom da página e revisar contraste em modo claro', 'Baixo', 'Médio'],
            ['P3', 'Testes em iOS Safari físico (instalação PWA e notificações)', 'Médio', 'Médio'],
        ],
        [0.14, 0.50, 0.14, 0.12], align_center_cols=(0, 2, 3)),
]))
story.append(Paragraph('Quadro 4 — Ações recomendadas, ordenadas por prioridade.', caption))
story.append(Spacer(1, 4))
story.append(para(
    'Conclusão: o Diário da Riqueza chega ao momento de divulgação com base '
    'técnica sólida — testes verdes, produção estável, prova social no ar e '
    'documentação legal publicada. O próximo salto não é de engenharia, e sim '
    'de distribuição: medir (analytics), professionalizar o endereço (domínio '
    'próprio) e iterar a mensagem com o que os números mostrarem. A fundação '
    'técnica está pronta para receber o tráfego.'))

doc = TocDocTemplate(
    OUT, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=MARGIN, bottomMargin=MARGIN,
    title=DOC_TITLE, author='Z.ai', creator='Z.ai',
    subject='Auditoria de prontidão para lançamento público',
)
doc.multiBuild(story, onFirstPage=footer, onLaterPages=footer)
print('OK ->', OUT)
